name: icgc
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  material_color_utilities: ^0.11.1
  shared_preferences: ^2.3.2
  flutter_dotenv: ^5.2.1
  cached_network_image: ^3.4.1
  http: ^1.2.2
  either_option: ^2.0.0
  awesome_icons: ^1.1.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  gap: ^3.0.1
  smooth_page_indicator: ^1.2.0+3
  pin_code_fields: ^8.0.1
  intl: ^0.19.0
  hive_flutter: ^1.1.0
  flutter_hooks: ^0.20.5
  flutter_slidable: ^3.1.1
  palette_generator: ^0.3.3+5
  # flutter_launcher_icons: ^0.13.1
  # flutter_native_splash: ^2.4.2
  nested: any
  # vocsy_epub_viewer: ^3.0.0
  dio: ^5.7.0
  carousel_slider: ^5.0.0
  flutter_widget_from_html_core: ^0.15.2
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  
  build_runner: ^2.4.11
  hive_generator: ^2.0.1
  
  

# flutter_launcher_icons:
#   android: true
#   ios: true
#   image_path: "assets/images/app_icon.png"

# flutter_native_splash:
#   color: "#214636" # Background color
#   image: assets/images/app_icon.png # Path to your splash image
#   android: true
#   ios: true
#   fullscreen: true
#   color_dark: "#000000"
#   android_12:
#     image: assets/images/app_icon_12.png

#   # Splash screen background color.
#     color: "#214636"



flutter:
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/themes/
    - assets/images/icgc_images/
    - assets/images/events_images/
    - assets/icons/
    - assets/json/

  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish/static/Mulish-Regular.ttf
          weight: 400
        - asset: assets/fonts/Mulish/static/Mulish-Medium.ttf
          weight: 500
        - asset: assets/fonts/Mulish/static/Mulish-Bold.ttf
          weight: 700

    - family: Playfair Display
      fonts:
        - asset: assets/fonts/Playfair/static/PlayfairDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/Playfair/static/PlayfairDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/Playfair/static/PlayfairDisplay-Bold.ttf
          weight: 700
        

    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi_Complete/Fonts/OTF/Satoshi-Light.otf
          weight: 300
        - asset: assets/fonts/Satoshi_Complete/Fonts/OTF/Satoshi-Regular.otf
          weight: 400
        - asset: assets/fonts/Satoshi_Complete/Fonts/OTF/Satoshi-Medium.otf
          weight: 500
        - asset: assets/fonts/Satoshi_Complete/Fonts/OTF/Satoshi-Bold.otf
          weight: 700
        - asset: assets/fonts/Satoshi_Complete/Fonts/OTF/Satoshi-Black.otf
          weight: 900
